name: e_shop
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  flutter_screenutil: ^5.9.0
  font_awesome_flutter: ^10.6.0
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.4
  flutter_local_notifications: ^16.1.0
  connectivity_plus: ^5.0.2
  dio: ^5.4.0
  loader_overlay: ^2.3.0
  firebase_auth: ^4.15.3
  google_sign_in: ^6.1.4
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  razorpay_flutter: ^1.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/


